services:
  mqtt:
    build: ./mqtt
    ports:
      - "1885:1883"
      - "15674:15672"
      - "5674:5672"
    environment:
      RABBITMQ_DEFAULT_USER: lapin
      RABBITMQ_DEFAULT_PASS: lapin
    restart: unless-stopped

  producer:
    build: ./gateway-mqtt
    command: [ "python", "send.py" ]
    depends_on:
      - mqtt
