version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
      - '1883:1883' # MQTT port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq_network

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
    working_dir: /app
    command: python manage_rabbitmq.py
    networks:
      - rabbitmq_network

  mqtt-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mqtt-client
    depends_on:
      - python-app
    volumes:
      - ./client:/client
    working_dir: /client
    command: python mqtt_client.py
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    driver: bridge